version: '3.8'

services:
  notebook:
    image: jupyter/jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - jnb-data:/home/jovyan
      - jnb-libs:/opt/conda/lib
    networks:
      - defaulf
    restart: unless-stopped

volumes:
  jnb-data:
  jnb-libs:

networks:
  defaulf:
    driver: bridge
